AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for github-actions-with-aws-sam

Globals:
  Function:
    Timeout: 100
    LoggingConfig:
      LogFormat: JSON

Resources:
  NetCodeWebAPIServerless:
    Type: AWS::Serverless::Function
    Properties:
      Description: A simple example includes a .NET Core WebAPI App with DynamoDB table.
      CodeUri: ./src/ServerlessAPI/
      Handler: ServerlessAPI
      Runtime: dotnet8
      MemorySize: 1024
      Environment:
        Variables:
          SAMPLE_TABLE: !Ref SampleTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: github-actions-with-aws-samBookCatalog
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /api/books/{proxy+}
            Method: ANY
        RootResource:
          Type: HttpApi
          Properties:
            PayloadFormatVersion: '2.0'
            Path: /
            Method: ANY

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod

  SampleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: github-actions-with-aws-samBookCatalog
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
