on:
  push:
    branches:
      - master
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
      - uses: aws-actions/setup-sam@v1
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1
      # Pull the Docker image explicitly
      - run: docker pull public.ecr.aws/sam/build-dotnet8:latest-x86_64
      # sam build 
      - run: sam build --use-container --mount-with WRITE

# Run Unit tests- Specify unit tests here 

# sam deploy
      - run: sam deploy --debug --no-confirm-changeset --s3-bucket je-github-actions-sam --no-fail-on-empty-changeset --capabilities CAPABILITY_IAM --region eu-north-1